---
name: Auto-deployment of linkml registry Documentation

on:
  release:
    types: [created]
  workflow_dispatch:
    types: trigger-deploy-docs

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # otherwise, you will fail to push refs to dest repo

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: uv sync

      - name: Build documentation.
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          make gendoc
          ([ ! -f docs/about.md ] && cp src/docs/about.md docs/) || true
          uv run mkdocs gh-deploy
